**CAPM AND Beta Estimation for Public Companies**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

In [ ]:
ticker = ['^GSPC' , 'BX' , 'ACN' , 'CTSH'] #S&P 500, BLACKSTONE, ACCENTURE, COGNIZANT
start_date = "2025-01-01"
end_date = "2026-01-01"
df = yf.download(ticker,start_date,end_date)
df

/tmp/ipykernel_5441/1242238573.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker,start_date,end_date)
[*********************100%***********************]  4 of 4 completed

Price            Close                                            High  \
Ticker             ACN          BX       CTSH        ^GSPC         ACN
Date
2025-01-02  341.018036  165.078705  74.289543  5868.549805  346.874049
2025-01-03  345.935486  167.130890  74.260368  5942.470215  346.883791
2025-01-06  343.471832  166.066772  73.803421  5975.379883  346.561157
2025-01-07  348.418701  162.788940  73.521461  5909.029785  355.095923
2025-01-08  349.728729  165.287720  73.910362  5918.250000  355.467431
...                ...         ...        ...          ...         ...
2025-12-24  267.709747  152.370819  84.392448  6932.049805  269.633436
2025-12-26  268.810394  152.214111  84.540649  6929.939941  269.464848
2025-12-29  269.058289  151.939865  83.977509  6905.740234  270.972052
2025-12-30  267.729553  151.597061  83.127853  6896.240234  270.129217
2025-12-31  266.043854  150.970230  82.001564  6845.500000  268.651743

Price                                                  Low              \
Ticker              BX       CTSH        ^GSPC         ACN          BX
Date
2025-01-02  166.228324  75.699301  5935.089844  338.368628  162.484954
2025-01-03  167.349407  75.057612  5949.339844  341.281943  164.784159
2025-01-06  169.639132  75.077065  6021.040039  341.829416  165.829249
2025-01-07  167.235383  74.658991  6000.680176  345.896391  160.062178
2025-01-08  165.506237  73.958978  5927.890137  347.401957  161.515848
...                ...        ...          ...         ...         ...
2025-12-24  153.164160  84.471488  6937.319824  267.471745  151.303223
2025-12-26  152.791975  84.629571  6945.770020  267.233768  151.205294
2025-12-29  153.085803  84.738243  6920.209961  267.679993  151.646031
2025-12-30  152.449165  83.829312  6913.250000  267.253579  150.989816
2025-12-31  152.008430  83.424244  6901.419922  266.043854  150.098533

Price                                     Open                         \
Ticker           CTSH        ^GSPC         ACN          BX       CTSH
Date
2025-01-02  74.065923  5829.529785  345.202305  164.480141  75.329849
2025-01-03  73.618688  5888.660156  342.171592  166.266302  74.727051
2025-01-06  73.550634  5960.009766  344.918740  169.107082  74.124258
2025-01-07  73.200618  5890.680176  347.401954  166.266284  73.686742
2025-01-08  72.704776  5874.779785  352.925579  162.370927  73.521469
...               ...          ...         ...         ...        ...
2025-12-24  83.868825  6904.910156  267.759315  152.458965  83.977503
2025-12-26  83.977506  6921.600098  267.630399  152.223900  84.145460
2025-12-29  83.888595  6888.759766  268.701330  152.419779  84.303541
2025-12-30  83.078452  6893.470215  268.155930  151.636247  83.523043
2025-12-31  81.932406  6844.549805  267.471747  150.833110  83.127850

Price                     Volume
Ticker            ^GSPC      ACN       BX     CTSH       ^GSPC
Date
2025-01-02  5903.259766  2253600  2393000  2196000  3621680000
2025-01-03  5891.069824  2029700  1600600  2570700  3667340000
2025-01-06  5982.810059  2356300  2203100  3248700  4940120000
2025-01-07  5993.259766  4663100  2729100  1860300  4517330000
2025-01-08  5910.660156  2216900  2237200  2407500  4441740000
...                 ...      ...      ...      ...         ...
2025-12-24  6904.910156  1062700  1432900  1687900  1798270000
2025-12-26  6936.020020  1411900  1403900  1612900  2586550000
2025-12-29  6903.600098  2753800  1508400  3657500  3541750000
2025-12-30  6900.439941  1784800  1429400  2723200  3309930000
2025-12-31  6898.819824  1973000  1843100  2501900  3261830000

[250 rows x 20 columns]

In [ ]:
#Beta = Covariance(stock returns, market returns) / Variance(market returns)

In [ ]:
returns = df['Close'].pct_change(fill_method=None).dropna()
market_returns = returns['^GSPC']
stock_returns = returns[['BX', 'ACN', 'CTSH']]

In [ ]:
beta_bx = np.cov(stock_returns['BX'], market_returns)[0, 1] / np.var(market_returns)
beta_acn = np.cov(stock_returns['ACN'], market_returns)[0 ,1] / np.var(market_returns)
beta_ctsh = np.cov(stock_returns['CTSH'] , market_returns)[0,1] /np.var(market_returns)
print(f"The beta for Blackstone is {beta_bx}")
print(f"The beta for Accenture is {beta_acn}")
print(f"The beta for Cognizant is {beta_ctsh}")

The beta for Blackstone is 1.5688534239120298
The beta for Accenture is 0.7899329016775525
The beta for Cognizant is 0.8647632337864603

In [ ]:
risk_free_rate = 0.045

In [ ]:
market_annual_return = (
    df['Close']['^GSPC'].iloc[-1]
    - df['Close']['^GSPC'].iloc[0]
) / df['Close']['^GSPC'].iloc[0]

In [ ]:
expected_return_bx = risk_free_rate + beta_bx * (market_annual_return - risk_free_rate)
expected_return_acn = risk_free_rate + beta_acn * (market_annual_return - risk_free_rate)
expected_return_ctsh = risk_free_rate + beta_ctsh * (market_annual_return - risk_free_rate)

In [ ]:
first_price_bx = df['Close']['BX'].iloc[0]
last_price_bx = df['Close']['BX'].iloc[-1]
actual_annual_return_bx = (last_price_bx - first_price_bx) / first_price_bx

In [ ]:
first_price_acn = df['Close']['ACN'].iloc[0]
last_price_acn = df['Close']['ACN'].iloc[-1]
actual_annual_return_acn = (last_price_acn - first_price_acn) / first_price_acn

In [ ]:
first_price_ctsh = df['Close']['CTSH'].iloc[0]
last_price_ctsh = df['Close']['CTSH'].iloc[-1]
actual_annual_return_ctsh = (last_price_ctsh - first_price_ctsh) / first_price_ctsh

In [ ]:
alpha_bx = actual_annual_return_bx - expected_return_bx
alpha_acn = actual_annual_return_acn - expected_return_acn
alpha_ctsh = actual_annual_return_ctsh - expected_return_ctsh

In [ ]:
final = pd.DataFrame({
    "stock": ["BX", "ACN", "CTSH"],
    "start_date": [start_date, start_date, start_date],
    "end_date": [end_date, end_date, end_date],
    "beta": [beta_bx, beta_acn, beta_ctsh],
    "alpha": [alpha_bx, alpha_acn, alpha_ctsh],
    "annual_return": [
        actual_annual_return_bx,
        actual_annual_return_acn,
        actual_annual_return_ctsh
    ],
    "expected_return": [
        expected_return_bx,
        expected_return_acn,
        expected_return_ctsh
    ]
})

final[['beta']] = final[['beta']].round(3)
final[['alpha','annual_return','expected_return']] = final[['alpha','annual_return','expected_return']].applymap(lambda x: f"{x:.2%}")

final

/tmp/ipykernel_5441/472376017.py:20: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  final[['alpha','annual_return','expected_return']] = final[['alpha','annual_return','expected_return']].applymap(lambda x: f"{x:.2%}")

  stock  start_date    end_date   beta    alpha annual_return expected_return
0    BX  2025-01-01  2026-01-01  1.569  -32.10%        -8.55%          23.56%
1   ACN  2025-01-01  2026-01-01  0.790  -36.08%       -21.99%          14.10%
2  CTSH  2025-01-01  2026-01-01  0.865   -4.62%        10.38%          15.00%

In [ ]:
#Blackstone emerged with a beta of 1.569 which means that the stock is more volatile than the market while Accenture and Cognizant showed a beta of 0.790 and 0.865 respectively meaning that the stock is less volatile than the market
#Cognizant showed the least negative alpha (-4.62%) meaning the difference between actual return and expected return is much lesser compard to blackstone and accenture making it a more reliable stock for an investor
#Analyzing the table we see that all the stocks underperformed with respect to CAPM expectations showing high volatility in the market paired with uncertainty.